pipeline {
    agent any

    tools {
        // Install the Maven version configured as "maven-local-3.6.3" and add it to the path.
        maven "maven-local-3.6.3"
    }

    stages {
        stage('Prepare') {
            steps {
                // Clean workspace prior to installation
                cleanWS()
            }
        }
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git url: 'https://github.com/ProtossGP32/libraryH2command.git'

                // Run Maven on a Unix agent.
                sh "mvn -Dmaven.test.failure.ignore=true clean spring-boot:build-image"

                // To run Maven on a Windows agent, use
                // bat "mvn -Dmaven.test.failure.ignore=true clean spring-boot:build-image"
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    // Comment until test dependencies are resolved
                    //junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts artifacts:'target/*.jar', fingerprint: true
                    // Docker-hub credentials
                    withCredentials([string(credentialsId: 'ff61ab9a-4aaf-46bd-955c-9025fb701738', variable: 'SECRET')]) { //set SECRET with the credential content
                        sh '''
                        echo "Docker credentials: '${SECRET}'"
                        '''
                    }
                }
            }
        }
    }
}